add_newline = false

palette = 'catppuccin_mocha'

format = '[┌──\(](blue)$username[@](mauve)$hostname[\)-\[](blue)$directory[\]](blue)$line_break[└─](blue)$character'

[username]
show_always = true
format = '[$user]($style)'
style_user = 'blue'
style_root = 'red'

[hostname]
ssh_only = false
format = '[$hostname]($style)'
style = 'green'

[directory]
format = '[$path]($style)'
style = 'green'
home_symbol = '~'
truncation_length = 0

[character]
success_symbol = '[\$](text)'
error_symbol = '[\$](red)'
vimcmd_symbol = '[\$](text)'

[palettes.catppuccin_mocha]
red = '#f38ba8'
green = '#a6e3a1'
blue = '#89b4fa'
mauve = '#cba6f7'
text = '#cdd6f4'
